const bands = [
  { id: 'blue', name: 'Visible blue–cyan', appearance: 'Visible · blue to cyan', color: '#24758d', summary: 'A timing signal through your eyes: helps the body clock respond to light and darkness.', absorber: 'Melanopsin in specialized retinal cells is particularly sensitive near 480 nm. Rods and cones also contribute to the light information these cells send.', pathway: 'Retinal signals reach the brain’s central clock, which coordinates daily timing across organs. Light can change circadian timing, alertness, pupil size, and melatonin secretion; the response depends on when and how much light reaches the eyes.', evidence: 'A laboratory study of human melanopsin found peak sensitivity near 479 nm. This is a pigment measurement, not a recommended outdoor exposure dose.', variables: 'Brightness, duration, biological time, previous light exposure, and the eye’s lens all matter. Blue light is part of normal daylight; bright light near sleep can have a different effect.', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3619500/', source: 'Human melanopsin experiment · Bailes & Lucas' },
  { id: 'red', name: 'Visible red', appearance: 'Visible · red', color: '#a94335', summary: 'Part of the daylight spectrum. Controlled red-light studies also explore effects on tissue function.', absorber: 'Cone pigments support seeing red. In cellular light-treatment research, mitochondrial cytochrome c oxidase is one proposed absorber of red light.', pathway: 'Photobiomodulation experiments investigate changes in mitochondrial activity and downstream cellular signaling. These proposed pathways are distinct from the eye-to-brain timing pathway.', evidence: 'A small human study using a controlled 670 nm light source reported improved color-contrast sensitivity after morning exposure. It did not test watching a sunrise or prove whole-body benefits from outdoor red light.', variables: 'Wavelength, delivered energy, tissue, and timing change results. A red-looking sky does not tell us the dose reaching tissue. Never look directly at the sun to seek this effect.', url: 'https://pubmed.ncbi.nlm.nih.gov/34819619/', source: 'Controlled 670 nm study · 2021' },
  { id: 'nir', name: 'Near-infrared (NIR)', appearance: 'Invisible · swatch is illustrative', color: '#805548', summary: 'Beyond visible red. Researchers study how controlled NIR exposure affects cellular energy and signaling.', absorber: 'Proposed absorbers include mitochondrial enzymes; water and other tissue components also absorb infrared energy, depending on wavelength.', pathway: 'Photobiomodulation research investigates mitochondrial respiration, nitric oxide, and redox signaling—chemical signals linked to a cell’s energy and stress response. Mechanisms vary with wavelength and are still being investigated.', evidence: 'Cell, animal, and human treatment studies use controlled devices. Their findings cannot establish an equivalent benefit or dose from ordinary sunlight. Cytochrome c oxidase is a proposed mechanism, not a universal explanation.', variables: 'Dose, power, tissue depth, and wavelength matter. NIR is invisible and is not confined to sunrise or sunset; visible sky color cannot measure it.', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5844808/', source: 'Mechanisms and mitochondrial signaling · research review' },
  { id: 'uva', name: 'UVA', appearance: 'Invisible · swatch is illustrative', color: '#73528f', summary: 'Acts on skin, including pigmentation and light-sensitive stores of nitric oxide.', absorber: 'Skin pigments and other molecules absorb UVA (315–400 nm). Light-sensitive nitrogen compounds in skin can contribute to nitric oxide release.', pathway: 'Nitric oxide helps relax blood vessels. UVA also affects pigmentation and can cause oxidative damage; these effects are not a command to seek a tan.', evidence: 'A controlled human irradiation experiment observed blood-vessel dilation and a reduction in blood pressure associated with release of nitric oxide from skin stores. It does not establish a safe daily sunlight treatment.', variables: 'Dose, skin characteristics, clouds, and surroundings change exposure. UVA and UVB overlap in sunlight. This app does not detect a UVA start time.', url: 'https://pubmed.ncbi.nlm.nih.gov/24445737/', source: 'Human UVA and nitric oxide experiment · Liu et al.' },
  { id: 'uvb', name: 'UVB', appearance: 'Invisible · swatch is illustrative', color: '#55538c', summary: 'Can start vitamin D production in skin; it also causes sunburn and DNA damage.', absorber: 'The skin molecule 7-dehydrocholesterol absorbs UVB and converts to previtamin D₃. UVB is conventionally defined as 280–315 nm; the atmosphere removes much of it.', pathway: 'Previtamin D₃ becomes vitamin D₃, followed by processing in the body to forms involved in calcium regulation and other physiology. This is a skin pathway, not a signal that requires looking at the sun.', evidence: 'UVB-driven vitamin D synthesis is established. The amount an individual makes outdoors cannot be inferred from clock time or a colored sky.', variables: 'Solar elevation, season, ozone, latitude, skin pigmentation, age, clothing, and exposed area matter. Use sun protection; the card does not prescribe a tanning or vitamin D exposure time.', url: 'https://www.who.int/news-room/questions-and-answers/item/radiation-the-known-health-effects-of-ultraviolet-radiation', source: 'UV effects and vitamin D · WHO' },
];

export function LightBandDetails() {
  return <section aria-label="Light pathways in detail"><h4>From a photon to a physiological response</h4>
    <p>A photon must be absorbed to start a biological response. Different molecules absorb different wavelengths; the result depends on the tissue and the amount of light. A wavelength is not a single instruction with the same effect everywhere.</p>
    <p>Wavelength describes the spacing of light waves, usually in nanometers (nm). Frequency describes how often they oscillate: shorter wavelengths have higher frequencies. The colored examples below cover selected bands, not every part of the spectrum.</p>
    {bands.map(band => <details key={band.id} className="go-deeper light-band-detail"><summary>{band.name} · explore the pathway</summary>
      <dl><dt>What absorbs it?</dt><dd>{band.absorber}</dd><dt>What happens next?</dt><dd>{band.pathway}</dd><dt>What has been observed?</dt><dd>{band.evidence}</dd><dt>What changes the response?</dt><dd>{band.variables}</dd></dl>
      <a href={band.url} target="_blank" rel="noopener noreferrer">{band.source} (opens in a new tab)</a>
    </details>)}
  </section>;
}
